version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000  
      JWT_SECRET: nsecret 
      MONGO_URI: mongodb://mongodb:27017/demo
      
    depends_on:
      - mongodb    
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
